version: "3.9"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty12345
      MONGO_INITDB_DATABASE: books
    networks:
      - counter_net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    networks:
      - counter_net
    depends_on:
      - mongodb
  counter:
    build: ./counter
    environment:
      - PORT=3002
    ports:
      - 81:3002
    networks:
      - counter_net
    volumes:
      - ./counter/data:/app/data
      - ./counter/data/counter_number.json:/app/data/counter_number.json
  books:
    build: ./book
    ports:
      - 80:3000
    networks:
      - counter_net
    volumes:
      - ./book/data:/app/data
      - ./book/data/books.json:/app/data/books.json
      - ./book:/app
    environment:
      - PORT=3000
      - COUNTER_PORT=3002
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-todos_database}
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb
networks:
  counter_net:
